[project]
authors = ["Sabrina Meindlhumer <sabrina.meindlhumer@protonmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "AoC2024"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.1.3,<3"
pandas = ">=2.2.3,<3"
python = ">=3.12.7,<3.13"
julia = ">=1.10.4,<1.11"
marimo = ">=0.10.9,<0.11"
matplotlib = ">=3.10.0,<4"
